#!/usr/bin/env python3
"""
Generate model.sh script for managing vLLM server via PM2.
"""

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Optional, Dict, Any


def parse_ecosystem_config(config_path: str) -> dict:
    """Parse ecosystem.config.js to extract app configuration."""
    config_path = Path(config_path)

    if not config_path.exists():
        raise FileNotFoundError(f"ecosystem.config.js not found at {config_path}")

    content = config_path.read_text()

    # Extract app name
    name_match = re.search(r"name:\s*['\"]([^'\"]+)['\"]", content)
    app_name = name_match.group(1) if name_match else "model-server"

    # Extract port from args
    port_match = re.search(r"'--port',\s*'(\d+)'", content)
    if not port_match:
        port_match = re.search(r"'--port',\s*\"(\d+)\"", content)
    port = int(port_match.group(1)) if port_match else 8000

    # Extract model ID from args (handle both single and double quotes)
    model_match = re.search(r"serve['\"]?,\s*['\"]([^'\"]+)['\"]", content)
    model_id = model_match.group(1) if model_match else "unknown"

    # Extract venv path from script
    script_match = re.search(r"script:\s*'([^']+\.venv[^']*)'", content)
    venv_path = None
    if script_match:
        venv_path = script_match.group(1)
        # Extract venv directory
        venv_match = re.search(r"(.+\.venv)/bin/vllm", venv_path)
        if venv_match:
            venv_path = venv_match.group(1)

    # Extract error/out log paths
    error_file_match = re.search(r"error_file:\s*'([^']+)'", content)
    out_file_match = re.search(r"out_file:\s*'([^']+)'", content)

    error_file = (
        error_file_match.group(1) if error_file_match else "logs/server.err.log"
    )
    out_file = out_file_match.group(1) if out_file_match else "logs/server.out.log"

    return {
        "app_name": app_name,
        "port": port,
        "model_id": model_id,
        "venv_path": venv_path,
        "error_file": error_file,
        "out_file": out_file,
    }


def generate_model_sh(
    config: dict,
    model_dir: str,
    output_file: Optional[str] = None,
) -> str:
    """Generate model.sh script content."""

    app_name = config["app_name"]
    port = config["port"]
    model_id = config["model_id"]
    venv_path = config.get("venv_path")
    error_file = config["error_file"]
    out_file = config["out_file"]

    # Build venv activation
    if venv_path:
        venv_activate = f'source "{venv_path}/bin/activate"'
    else:
        venv_activate = 'if [ -d "$SCRIPT_DIR/.venv" ]; then source "$SCRIPT_DIR/.venv/bin/activate"; fi'

    # Use string concatenation instead of f-string to avoid brace escaping issues
    script = (
        """#!/bin/bash
#
# model.sh - Manage vLLM server for """
        + model_id
        + '''
#
# Generated by model-server-generator
#
# Usage: ./model.sh <command>
#
# Commands:
#   start     - Start the server
#   stop      - Stop the server
#   restart   - Restart the server
#   status    - Check server status
#   logs      - View server logs
#   errors    - View error logs
#   health    - Check health endpoint
#   url       - Print server URL
#   info      - Print model info
#   activate  - Activate virtual environment
#   help      - Show this help
#

set -e

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ECOSYSTEM_FILE="$SCRIPT_DIR/ecosystem.config.js"
APP_NAME="'''
        + app_name
        + """"
PORT="""
        + str(port)
        + '''
MODEL_ID="'''
        + model_id
        + """"

# Colors
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
CYAN='\\033[0;36m'
NC='\\033[0m'

# Logging
log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_ok() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check prerequisites
check_pm2() {
    if ! command -v pm2 &> /dev/null; then
        log_error "pm2 not found. Install with: npm install -g pm2"
        exit 1
    fi
}

check_config() {
    if [ ! -f "$ECOSYSTEM_FILE" ]; then
        log_error "ecosystem.config.js not found at $ECOSYSTEM_FILE"
        log_info "Run setup_model.sh first to generate configuration"
        exit 1
    fi
}

# Activate virtual environment if exists
activate_venv() {
    """
        + venv_activate
        + """
}

# Commands
cmd_start() {
    check_pm2
    check_config
    
    log_info "Starting $APP_NAME..."
    
    # Check if already running
    if pm2 describe "$APP_NAME" &> /dev/null; then
        local status=$(pm2 jlist | jq -r ".[] | select(.name == \\"$APP_NAME\\") | .pm2_env.status")
        if [ "$status" = "online" ]; then
            log_warn "Server is already running"
            cmd_status
            return
        fi
    fi
    
    # Create logs directory
    mkdir -p "$SCRIPT_DIR/logs"
    
    # Start with PM2
    pm2 start "$ECOSYSTEM_FILE"
    
    log_ok "Server started"
    log_info "Waiting for server to be ready..."
    
    # Wait for health endpoint
    local max_wait=300
    local waited=0
    while [ $waited -lt $max_wait ]; do
        if curl -s "http://localhost:$PORT/health" > /dev/null 2>&1; then
            log_ok "Server is healthy and ready!"
            cmd_url
            return
        fi
        sleep 2
        waited=$((waited + 2))
        echo -n "."
    done
    
    echo ""
    log_warn "Server started but health check timed out"
    log_info "Check logs: ./model.sh logs"
}

cmd_stop() {
    check_pm2
    
    log_info "Stopping $APP_NAME..."
    pm2 stop "$APP_NAME" 2>/dev/null || log_warn "Server not running"
    log_ok "Server stopped"
}

cmd_restart() {
    check_pm2
    check_config
    
    log_info "Restarting $APP_NAME..."
    pm2 restart "$ECOSYSTEM_FILE" 2>/dev/null || cmd_start
    log_ok "Server restarted"
}

cmd_delete() {
    check_pm2
    
    log_info "Deleting $APP_NAME from PM2..."
    pm2 delete "$APP_NAME" 2>/dev/null || log_warn "Server not in PM2"
    log_ok "Server deleted from PM2"
}

cmd_status() {
    check_pm2
    
    echo ""
    pm2 describe "$APP_NAME" 2>/dev/null || log_warn "Server not running"
    echo ""
    
    # Show GPU status if available
    if command -v nvidia-smi &> /dev/null; then
        log_info "GPU Status:"
        nvidia-smi --query-gpu=index,name,utilization.gpu,memory.used,memory.total --format=csv,noheader,nounits | \\
            awk -F', ' '{printf "  GPU %s: %s | Util: %s%% | VRAM: %s/%s MB\\n", $1, $2, $3, $4, $5}'
    fi
}

cmd_logs() {
    check_pm2
    pm2 logs "$APP_NAME" --lines 100
}

cmd_errors() {
    local err_file="$SCRIPT_DIR/"""
        + error_file
        + """"
    if [ -f "$err_file" ]; then
        echo -e "${RED}=== Last 50 error log lines ===${NC}"
        tail -50 "$err_file"
    else
        log_info "No error log found at $err_file"
    fi
}

cmd_health() {
    log_info "Checking health endpoint..."
    
    local response
    response=$(curl -s -w "\\n%{http_code}" "http://localhost:$PORT/health" 2>/dev/null)
    local http_code=$(echo "$response" | tail -n1)
    local body=$(echo "$response" | head -n -1)
    
    if [ "$http_code" = "200" ]; then
        log_ok "Server is healthy"
        echo "$body" | jq . 2>/dev/null || echo "$body"
    else
        log_error "Health check failed (HTTP $http_code)"
        return 1
    fi
}

cmd_url() {
    echo "Server URL: http://localhost:$PORT"
    echo "OpenAI API: http://localhost:$PORT/v1"
    echo ""
    echo "Test with curl:"
    echo "  curl http://localhost:$PORT/v1/models"
    echo ""
    echo "Chat completion:"
    echo "  curl http://localhost:$PORT/v1/chat/completions \\"
    echo "    -H 'Content-Type: application/json' \\"
    echo "    -d '{"
    echo "      \"model\": \"$MODEL_ID\","
    echo "      \"messages\": [{\"role\": \"user\", \"content\": \"Hello!\"}]"
    echo "    }'"
}

cmd_info() {
    local info_file="$SCRIPT_DIR/model_info.json"
    if [ -f "$info_file" ]; then
        echo -e "${CYAN}=== Model Information ===${NC}"
        cat "$info_file" | jq .
    else
        log_info "No model_info.json found"
    fi
}

cmd_activate() {
    activate_venv
    echo "Virtual environment activated"
    echo "Python: $(which python)"
    echo "vLLM: $(python -c 'import vllm; print(vllm.__version__)')"
    exec bash
}

cmd_help() {
    echo "Usage: $0 <command>"
    echo ""
    echo "Commands:"
    echo "  start       Start the vLLM server"
    echo "  stop        Stop the server"
    echo "  restart     Restart the server"
    echo "  delete      Remove server from PM2"
    echo "  status      Show server and GPU status"
    echo "  logs        View server logs (PM2)"
    echo "  errors      View error logs"
    echo "  health      Check health endpoint"
    echo "  url         Print server URL and test commands"
    echo "  info        Show model information"
    echo "  activate    Activate virtual environment"
    echo "  help        Show this help message"
    echo ""
    echo "Model: $MODEL_ID"
    echo "Port: $PORT"
    echo "App: $APP_NAME"
}

# Main
case "${1:-help}" in
    start)
        cmd_start
        ;;
    stop)
        cmd_stop
        ;;
    restart)
        cmd_restart
        ;;
    delete)
        cmd_delete
        ;;
    status)
        cmd_status
        ;;
    logs)
        cmd_logs
        ;;
    errors)
        cmd_errors
        ;;
    health)
        cmd_health
        ;;
    url)
        cmd_url
        ;;
    info)
        cmd_info
        ;;
    activate)
        cmd_activate
        ;;
    help|--help|-h)
        cmd_help
        ;;
    *)
        log_error "Unknown command: $1"
        cmd_help
        exit 1
        ;;
esac
"""
    )

    # Write to file if specified
    if output_file:
        output_path = Path(output_file)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(script)
        output_path.chmod(0o755)
        print(f"Script written to: {output_file}")

    return script


def generate_model_sh_func(
    model_dir: str, ecosystem_path: Optional[str] = None
) -> Dict[str, Any]:
    """Generate model.sh script for the model directory.

    Returns:
        Dict with 'success', 'script_path', and 'error' keys
    """
    result = {
        "success": False,
        "script_path": None,
        "error": None,
    }

    model_dir_path = Path(model_dir)
    eco_path = (
        Path(ecosystem_path)
        if ecosystem_path
        else model_dir_path / "ecosystem.config.js"
    )

    try:
        config = parse_ecosystem_config(eco_path)
    except FileNotFoundError as e:
        result["error"] = f"ecosystem.config.js not found: {e}"
        return result

    output_path = model_dir_path / "model.sh"

    script = generate_model_sh(
        config=config,
        model_dir=str(model_dir_path),
        output_file=str(output_path),
    )

    result["success"] = True
    result["script_path"] = str(output_path)
    return result


def main():
    parser = argparse.ArgumentParser(
        description="Generate model.sh script for PM2 server management"
    )
    parser.add_argument(
        "model_dir", help="Model directory containing ecosystem.config.js"
    )
    parser.add_argument(
        "-o",
        "--output",
        default="model.sh",
        help="Output file path (default: model.sh in model_dir)",
    )
    parser.add_argument(
        "--ecosystem",
        help="Path to ecosystem.config.js (default: model_dir/ecosystem.config.js)",
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="Print script without writing"
    )

    args = parser.parse_args()

    # Determine paths
    model_dir = Path(args.model_dir)
    ecosystem_path = args.ecosystem or model_dir / "ecosystem.config.js"

    # Parse ecosystem config
    try:
        config = parse_ecosystem_config(ecosystem_path)
    except FileNotFoundError as e:
        print(f"ERROR: {e}")
        print("Run generate_pm2_config.py first.")
        return 1

    print(f"App name: {config['app_name']}")
    print(f"Port: {config['port']}")
    print(f"Model: {config['model_id']}")

    # Determine output path
    if args.output == "model.sh":
        output_path = model_dir / "model.sh"
    else:
        output_path = Path(args.output)

    # Generate script
    script = generate_model_sh(
        config=config,
        model_dir=str(model_dir),
        output_file=None if args.dry_run else str(output_path),
    )

    if args.dry_run:
        print("\n" + "=" * 50)
        print(script)

    return 0


if __name__ == "__main__":
    sys.exit(main())
