module.exports = {
  apps: [{
    name: 'kimi-k2-5',
    // Pointing to the vllm binary inside the local .venv
    script: '/data/kimi-2.5/vllm/.venv/bin/vllm',
    args: [
      'serve',
      'moonshotai/Kimi-K2.5',
      '--host', '0.0.0.0',
      '--port', '8000',
      '--tensor-parallel-size', '8',
      '--max-model-len', '262000',
      '--kv-cache-dtype', 'auto',
      '--disable-log-requests',
      '--gpu-memory-utilization', '0.9',
      '--max-num-batched-tokens', '16384',
      '--chat-template', './chat_template.jinja',
      '--enable-prefix-caching',
      '--override-generation-config', '{"temperature": 1.0, "top_p": 0.95, "max_new_tokens": 131000}',
      '--served-model-name', 'kimi-k2-5', 'claude-haiku-4-5-20251001',
      '--swap-space', '50',
      '--decode-context-parallel-size', '8',
      '--mm-encoder-tp-mode', 'data',
      '--mm-processor-cache-type', 'shm',
      '--trust-remote-code',
      '--tokenizer-mode', 'hf',
      '--default-chat-template-kwargs', '{"thinking": true}',
      '--enable-chunked-prefill',
      '--max-num-seqs', '128',
      '--max-cudagraph-capture-size', '128',
      '--compilation-config', '{"cudagraph_mode": "FULL_AND_PIECEWISE"}',
      '--enable-auto-tool-choice',
      '--tool-call-parser', 'kimi_k2',
      '--reasoning-parser', 'kimi_k2',
      '--kv-cache-metrics',
      '--kv-cache-metrics-sample', '0.05'
    ],
    interpreter: 'none',
    cwd: '.',
    env: {
      HF_HOME: '/juspfsdata1/.cache/huggingface',
      CUDA_VISIBLE_DEVICES: '0,1,2,3,4,5,6,7',
      VLLM_ALLOW_LONG_MAX_MODEL_LEN: '1',
      TORCH_CUDA_MATMUL_PRECISION: 'high',
      PROMETHEUS_MULTIPROC_DIR: '/tmp/vllm_prometheus_multiproc',
      PYTHONHASHSEED: '0',
      PATH: '/usr/local/cuda-12.9/bin:/usr/bin:/bin:/usr/sbin:/sbin',
      CUDA_HOME: '/usr/local/cuda-12.9',
      LD_LIBRARY_PATH: '/usr/local/cuda-12.9/lib64:/usr/lib/x86_64-linux-gnu',
      CC: '/usr/bin/gcc',
      CXX: '/usr/bin/g++'
    },
    exec_mode: 'fork',
    instances: 1,
    autorestart: true,
    watch: false,
    max_restarts: 10,
    restart_delay: 5000,
    error_file: '/tmp/kimi-k2-5_server.err.log',
    out_file: '/tmp/kimi-k2-5_server.out.log',
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    merge_logs: true
  }]
};
